export default {
    products: [
      {
        _id: '0',
        name: 'Story Book',
        category: 'Books',
        image: '/images/d1.jpg',
        price: 250,
        brand: ' Papermate',
        rating: 4.2,
        numReviews: 5,
        countInStock: 6,
      },
      {
        _id: '1',
        name: 'Drawing Book',
        category: 'Books',
        image: '/images/d2.jpg',
        price: 160,
        brand: ' Classmate',
        rating: 4.5,
        numReviews: 10,
        countInStock: 7,
      },
      {
        _id: '2',
        name: 'Diary',
        category: 'Books',
        image: '/images/d3.jpg',
        price: 150,
        brand: ' Pearson',
        rating: 4.2,
        numReviews: 5,
        countInStock: 5,
      },
      {
        _id: '3',
        name: 'Nib pen',
        category: 'Stationery',
        image: '/images/p1.jpg',
        price: 70,
        brand: ' Trimax',
        rating: 4.5,
        numReviews: 8,
        countInStock: 10,
      }, {
        _id: '4',
        name: 'Ball Pen',
        category: 'Stationery',
        image: '/images/p2.jpg',
        price: 20,
        brand: ' Natraj',
        rating: 4.5,
        numReviews: 8,
        countInStock: 4,
      }, {
        _id: '5',
        name: 'Designer Pen',
        category: 'Stationery',
        image: '/images/p3.jpg',
        price: 20,
        brand: ' Papermate',
        rating: 4.5,
        numReviews: 8,
        countInStock: 8,
      },
    ]
}