export default {
    products: [
      {
        _id: '0',
        name: 'Story Book',
        category: 'Books',
        image: '/images/d1.jpg',
        price: 250,
        brand: ' Papermate',
        rating: 4.2,
        numReviews: 5,
        countInStock: 6,
      },
      {
        _id: '1',
        name: 'Drawing Book',
        category: 'Books',
        image: '/images/d2.jpg',
        price: 160,
        brand: ' Classmate',
        rating: 4.5,
        numReviews: 10,
        countInStock: 7,
      },
      {
        _id: '2',
        name: 'Diary',
        category: 'Books',
        image: '/images/d3.jpg',
        price: 150,
        brand: ' Pearson',
        rating: 4.2,
        numReviews: 5,
        countInStock: 5,
      },
      {
        _id: '3',
        name: 'Nib pen',
        category: 'Pen',
        image: '/images/p1.jpg',
        price: 70,
        brand: ' Trimax',
        rating: 4.5,
        numReviews: 8,
        countInStock: 10,
      }, {
        _id: '4',
        name: 'Ball Pen',
        category: 'Pen',
        image: '/images/p2.jpg',
        price: 20,
        brand: ' Natraj',
        rating: 4.5,
        numReviews: 8,
        countInStock: 4,
      }, {
        _id: '5',
        name: 'Designer Pen',
        category: 'Pen',
        image: '/images/p3.jpg',
        price: 20,
        brand: ' Papermate',
        rating: 4.5,
        numReviews: 8,
        countInStock: 8,
      }, {
        _id: '6',
        name: 'Pencil Colors',
        category: 'Colors',
        image: '/images/color-1.jpg',
        price: 20,
        brand: ' Papermate',
        rating: 4.5,
        numReviews: 8,
        countInStock: 8,
      }, {
        _id: '7',
        name: 'Colorful Pencils',
        category: 'Pencils',
        image: '/images/pencil-1.jpg',
        price: 20,
        brand: ' Papermate',
        rating: 4.5,
        numReviews: 8,
        countInStock: 4,
      }, {
        _id: '8',
        name: 'Drawing Book',
        category: 'Books',
        image: '/images/d4.jpg',
        price: 100,
        brand: ' Natraj',
        rating: 4.5,
        numReviews: 3,
        countInStock: 9,
      }, {
        _id: '9',
        name: 'Color Brushes',
        category: 'Brushes',
        image: '/images/brush-1.png',
        price: 20,
        brand: ' Papermate',
        rating: 4.5,
        numReviews: 8,
        countInStock: 8,
      }, {
        _id: '10',
        name: 'Paint Colors',
        category: 'Colors',
        image: '/images/color-3.jpg',
        price: 20,
        brand: ' Papermate',
        rating: 4.8,
        numReviews: 3,
        countInStock: 10,
      }, {
        _id: '11',
        name: 'Pencils',
        category: 'Pencil',
        image: '/images/pencil-2.png',
        price: 20,
        brand: ' Papermate',
        rating: 4.2,
        numReviews: 9,
        countInStock: 3,
      }, {
        _id: '12',
        name: 'Pencil Colors',
        category: 'Colors',
        image: '/images/color-2.jpg',
        price: 20,
        brand: ' Papermate',
        rating: 4.5,
        numReviews: 8,
        countInStock: 8,
      }, {
        _id: '13',
        name: 'Butterfly Diary',
        category: 'Books',
        image: '/images/d5.jpg',
        price: 20,
        brand: ' Papermate',
        rating: 4.5,
        numReviews: 8,
        countInStock: 8,
      },
      
    ]
}